name: Deploy to VM via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkpoint repository
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy//ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ./Dataops
          git pull
          docker build -t flask-api .
          docker stop flask-api || true
          docker rm flask-api || true
          docker run -d -p 5000:5000 --name flask-api flask-api
